export const contestant = [
  {
    id: 1,
    name: {
      ko: "히메나",
      en: "Himena",
    },
    fullName: "Higa Himena (比嘉妃菜)",
    age: "15",
    mbti: "INFJ",
    nationality: "Japanese",
    link: "qMly13ZwLSI",
  },
  {
    id: 2,
    name: {
      ko: "후우나",
      en: "Funa",
    },
    fullName: "Funa (후우나)",
    age: "21",
    mbti: "INFP",
    nationality: "Japanese",
    link: "yv9_JXtRft8",
  },
  {
    id: 3,
    name: {
      ko: "혜원",
      en: "Hyewon",
    },
    fullName: "Shin Hyewon (신혜원)",
    age: "17",
    mbti: "ISFP",
    nationality: "Korean",
    link: "mgHuXfkwnIE",
  },
  {
    id: 4,
    name: {
      ko: "하슬",
      en: "Haseul",
    },
    fullName: "Choi Haseul (최하슬)",
    age: "15",
    mbti: "ENFP",
    nationality: "Korean-American",
    link: "0z5x47q2L8o",
  },
  {
    id: 5,
    name: {
      ko: "지현",
      en: "Jihyun",
    },
    fullName: "Choi Jihyun (최지현)",
    age: "18",
    mbti: "ISFP or ISTP",
    nationality: "Korean",
    link: "WPrguyGE6WY",
  },
  {
    id: 6,
    name: {
      ko: "지우",
      en: "Jiwoo",
    },
    fullName: "Son Jiwoo (손지우)",
    age: "21",
    mbti: "ENFP",
    nationality: "Korean",
    link: "CbMrkVFSpc8",
  },
  {
    id: 7,
    name: {
      ko: "지민",
      en: "Jeemin",
    },
    fullName: "Bang Jeemin (방지민)",
    age: "18",
    mbti: "INFP",
    nationality: "Korean",
    link: "TR7UAesFyPA",
  },
  {
    id: 8,
    name: {
      ko: "정은",
      en: "Jeongeun",
    },
    fullName: "Choi Jeongeun (최정은)",
    age: "18",
    mbti: "ISTP",
    nationality: "Korean",
    link: "5wQUJ6zbeQk",
  },
  {
    id: 9,
    name: {
      ko: "이로하",
      en: "Iroha",
    },
    fullName: "Hokazono Iroha (外園 いろは)",
    age: "15",
    mbti: "ISFP",
    nationality: "Japanese",
    link: "EIQL1UyFyDo",
  },
  {
    id: 10,
    name: {
      ko: "윤아",
      en: "Yunah",
    },
    fullName: "No Yunah (노윤아)",
    age: "19",
    mbti: "ENFP",
    nationality: "Korean",
    link: "-6hFjKhT0NI",
  },
  {
    id: 11,
    name: {
      ko: "유이사",
      en: "Yuisa",
    },
    fullName: "Ura Yuisa (浦唯沙)",
    age: "16",
    mbti: "ISFJ",
    nationality: "Japanese",
    link: "yWHSVXyeg5k",
  },
  {
    id: 12,
    name: {
      ko: "원희",
      en: "Wonhee",
    },
    fullName: "Lee Wonhee (이원희)",
    age: "15",
    mbti: "ISFP",
    nationality: "Korean",
    link: "FgejW5SgnOA",
  },
  {
    id: 13,
    name: {
      ko: "예원",
      en: "Yewon",
    },
    fullName: "Son Yewon (손예원)",
    age: "18",
    mbti: "ISFJ",
    nationality: "Korean",
    link: "n3tJN-N8jMg",
  },
  {
    id: 14,
    name: {
      ko: "영서",
      en: "Youngseo",
    },
    fullName: "Lee Youngseo (이영서)",
    age: "17",
    mbti: "ESTJ",
    nationality: "Korean",
    link: "YMHeNurKaso",
  },
  {
    id: 15,
    name: {
      ko: "에나",
      en: "Ena",
    },
    fullName: "Sakata Ena (坂田 絵奈)",
    age: "12",
    mbti: "ESFP",
    nationality: "Japanese",
    link: "zSYfHEO5S3Y",
  },
  {
    id: 16,
    name: {
      ko: "아이리스",
      en: "Iris",
    },
    fullName: "Pornkanok Niyomwanit (พรกนก นิยมวานิช)",
    age: "15",
    mbti: "ENFP",
    nationality: "Thai",
    link: "C_kQf9tG1JY",
  },
  {
    id: 17,
    name: {
      ko: "서연",
      en: "Seoyeon",
    },
    fullName: "Hong Seoyeon (홍서연)",
    age: "15",
    mbti: "INFP",
    nationality: "Korean",
    link: "k3zxEy19Qj0",
  },
  {
    id: 18,
    name: {
      ko: "샤넬",
      en: "Chanelle",
    },
    fullName: "Chanelle Moon Thomas",
    age: "19",
    mbti: "INFJ",
    nationality: "American-Korean",
    link: "BJHh9GLQuKk",
  },
  {
    id: 19,
    name: {
      ko: "민주",
      en: "Minju",
    },
    fullName: "Park Minju (박민주)",
    age: "19",
    mbti: "ISTP",
    nationality: "Korean",
    link: "EWEp7cR-CVc",
  },
  {
    id: 20,
    name: {
      ko: "모카",
      en: "Moka",
    },
    fullName: "Sakai Moka (さかい もか)",
    age: "18",
    mbti: "ISFP",
    nationality: "Japanese",
    link: "WalF1HujtXY",
  },
  {
    id: 21,
    name: {
      ko: "모아",
      en: "Moa",
    },
    fullName: "Premyuda Meeboonrod (เปรมยุดา มีบุญรอด)",
    age: "21",
    mbti: "ESFJ",
    nationality: "Thai",
    link: "mqX4sPWYO9c",
  },
  {
    id: 22,
    name: {
      ko: "루카",
      en: "Ruka",
    },
    fullName: "Shimazaki Haruka (島崎遥香)",
    age: "18",
    mbti: "ISFJ",
    nationality: "Japanese",
    link: "6F4D_ZCJ_tQ",
  },
];
